name: flutter_sample
description: A new Flutter project.
version: 1.0.0+1

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Mock
  mockito: ^5.4.2

  # Static analysis
  pedantic_mono: ^1.23.0

flutter:
  uses-material-design: true