name: flutter_sample
description: A new Flutter project.
version: 1.0.0+1

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

  # Riverpod
  flutter_riverpod: ^2.3.6

  # DI
  get_it: ^7.6.0

  # Local Database
  shared_preferences: ^2.2.0
  flutter_secure_storage: ^8.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter

  # Mock
  mockito: ^5.4.2

  # Static analysis
  pedantic_mono: ^1.23.0

flutter:
  uses-material-design: true